name: Build App for Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build application
      run: npm run build
      
    - name: Create deployment zip
      run: zip -r myapp-$(date +%Y%m%d-%H%M%S).zip . -x "*.git*" "node_modules/*" "*.md" ".github/*"
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: deployment-package
        path: myapp-*.zip
